# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo v2
        uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Running CI Installation
        run: npm ci
      - name: Running Application Unit Tests
        run: npm test
  
  deploy:
    
    runs-on: ubuntu-latest
    
    needs: [test]
    
    steps:
      - name: Checkout Repo v2
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
        
      - name: Deploying to Heroku
        env:
          TOKEN: ${{ secrets.HEROKU_TOKEN }}
          APP: ${{ secrets.HEROKU_APP }}
        run: |
          git remote add heroku https://heroku:$TOKEN@git.heroku.com/$APP.git
          git push heroku HEAD:master -f
